# Based on targets::tar_github_actions()

on:
  push:
    branches:
      - main

name: Deploy

jobs:
  targets:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4"

      - name: Install pandoc for {rmarkdown}
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install system dependencies
        run: |
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libssl-dev
          sudo apt-get install libzmq3-dev
          sudo apt-get install libglpk-dev

      - name: Install R dependencies
        uses: r-lib/actions/setup-renv@v2

      - name: Install cmdstan
        shell: Rscript {0}
        run: |
          cmdstanr::install_cmdstan()

      - name: Run targets pipeline
        shell: Rscript {0}
        run: |
          options(crayon.enabled = TRUE)
          targets::tar_make()

      - name: Remove gitignore files from github pages folder for deploy
        run: |
          find output/github-pages -name ".gitignore" -type f -delete

      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: output/github-pages
